Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DBC.Ors.Models;
using DBC.Ors.Services;
using DBC.WeChat.Models.Conversation;
using DBC.WeChat.UI.Components;
using DBC.WeChat.UI.Mvc;

namespace DBC.WeChat.UI.Store.Controllers
{
    public class ActivityController : BaseController
    {

        public ActionResult Index()
        {
            var query = new ActivityQuery()
            {
                OwnerID = OwnerID,
                Take = PageSize,
                OrderField = "LastModifiedAt",
                OrderDirection = OrderDirection.Desc,
            };
            var initList = Service.Select(query).ToArray();
            ViewData["Pagination"] = Pagination.FromQuery(query);
            ViewData["Query"] = query;
            return View(initList);
        }

        [HttpPost]
        public ActionResult AjaxQuery(ActivityQuery query)
        {
            query.OwnerID = OwnerID;
            var activityList=Service.Select(query);
            var pro = Pagination.FromQuery(query);
            ViewData["Pagination"] = pro;
            return PartialView("Activity/ActivityList", activityList);
        }


        public ActionResult Add(int type)
        {
            var activity = new Activity()
            {
                OwnerID = OwnerID,
                Type = type,
            };
            return PartialView("Add",activity);
        }

        [HttpPost]
        public ActionResult Add(Activity activity)
        {
            activity.AwardTypes = GetTypes();
            var query = new ActivityQuery()
            {
                OwnerID = OwnerID,
                Take = PageSize,
                OrderField = "LastModifiedAt",
                OrderDirection = OrderDirection.Desc,
            };
            try
            {
                activity.RuleType = activity.RuleType ?? 1;
                Service.Create(activity);
                return AjaxQuery(query);
            }
            catch (RuleViolatedException exception)
            {
                ViewBag.Error = exception.Message;
                return AjaxQuery(query);
            }
        }


        public ActionResult Edit(long id)
        {
            var activity = Service.SelectOrEmpty(new ActivityQuery()
            {
                OwnerID = OwnerID,
                IDs = new long[]{id},
                Includes = new []{"AwardTypes"},
            }).FirstOrDefault();
            return View(activity);
        }

        [HttpPost]
        public ActionResult Edit(Activity activity)
        {
            try
            {
                activity.AwardTypes = GetTypes();
                if (activity.State == (int)ActivityState.Started || activity.State == (int)ActivityState.End)
                {
                    ViewBag.Error = "启用或终止状态的活动不能编辑";
                }
                else
                {
                    Service.Update(activity);
                }
                return PartialView(activity);
            }
            catch (RuleViolatedException exception)
            {
                ViewBag.Error = exception.Message;
                activity = Service.SelectOrEmpty(new ActivityQuery()
                {
                    OwnerID = OwnerID,
                    IDs = new long[] { activity.ID.Value },
                    Includes = new[] { "AwardTypes" },
                }).FirstOrDefault();
                return PartialView(activity);
            }
        }

        [HttpPost]
        public JsonResult ChangeState(long id, int state)
        {
            var response = new JsonResult()
            {
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
            if (CheckState(id, state))
            {
                Service.Update(new Activity()
                {
                    ID=id,
                    State = state
                });
                response.Data = new {success = true};
            }
            else
            {
                response.Data = new {success = false,msg="同类型活动只能有一个启用"};
            }
            return response;
        }

        [HttpPost]
        public JsonResult DeleteAward(long activityid,long id)
        {
            var response = new JsonResult()
            {
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
            };
            var activity = Service.SelectOrEmpty(new ActivityQuery()
            {
                IDs = new long[] {activityid}
            }).FirstOrDefault();
            if (activity == null||activity.State==(int)ActivityState.Started)
            {
                response.Data = new {success = false,msg="活动启用中或者不存在"};
                return response;
            }
            Service.Delete(new AwardType()
            {
                ID=id
            });
            response.Data = new {success=true};
            return response;
        }


        private bool CheckState(long id, int state)
        {
            var activity = Service.SelectOrEmpty(new ActivityQuery()
            {
                IDs=new long[]{id},
                OwnerID = OwnerID,
            }).FirstOrDefault();
            if (activity == null)
                return false;
            if (activity.State == (int) ActivityState.End)
                return false;
            if (state == (int) ActivityState.Started)
            {
                //当前类型的活动只有一个启用状态
                var started = Service.SelectOrEmpty(new ActivityQuery()
                {
                    Type = activity.Type,
                    State = (int)ActivityState.Started,
                    OwnerID = OwnerID,
                }).FirstOrDefault();
                if (started != null)
                {
                    return false;
                }
            }
            return true;
        }

        private ICollection<AwardType> GetTypes()
        {
            var response = new Collection<AwardType>();
            var count = Convert.ToInt32(Request.Form["AwardTypeCount"]);
            for (int i = 0; i < count; i++)
            {
                var awardType = new AwardType()
                {
                    ID= !string.IsNullOrEmpty(Request.Form["ID"+i])?Convert.ToInt32(Request.Form["ID"+i]):0,
                    OwnerID = OwnerID,
                    TypeName = Request.Form["TypeName"+i],
                    Name = Request.Form["Name"+i],
                    Count = !string.IsNullOrEmpty(Request.Form["Count" + i])? Convert.ToInt32(Request.Form["Count" + i]):0,
                    Probability = !string.IsNullOrEmpty(Request.Form["Probality" + i]) ? Convert.ToDecimal(Request.Form["Probality" + i]) : 0,
                    Reply = Request.Form["Reply"+i],
                };
                response.Add(awardType);
            }
            return response;
        }
    }
}

Controllers/AwardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DBC.Ors.Models;
using DBC.WeChat.Models.Conversation;
using DBC.WeChat.UI.Components;
using DBC.WeChat.UI.Mvc;
using DBC.WeChat.UI.Store.Models;

namespace DBC.WeChat.UI.Store.Controllers
{
    public class AwardController : BaseController
    {

        public ActionResult Index(long activityID)
        {
            ViewBag.ActivityID = activityID;
            var query=new AwardQuery()
            {
                Take =  PageSize,
                OrderField =  "LastModifiedAt",
                OrderDirection = OrderDirection.Desc,
            };
            var awardtypes = Service.Select(new AwardTypeQuery()
            {
                ActivityID = activityID,
                OwnerID = OwnerID,
                Take = PageSize,
            }).ToArray();
            if (!awardtypes.Any())
            {
                var pro = Pagination.FromQuery(query);
                ViewData["Pagination"] = pro;
                ViewData["Query"] = query;
                return View();
            }
            else
            {
                query.Take = query.Take ?? PageSize;
                query.OrderField = query.OrderField ?? "LastModifiedAt";
                query.OrderDirection = query.OrderDirection ?? OrderDirection.Desc;
                query.AwardTypeIDs = awardtypes.Select(o => o.ID).OfType<long>().ToArray();
                var initList = Service.Select(query).ToArray();
                initList = initList.Select(o =>
                {
                    o.AwardType = awardtypes.FirstOrDefault(p => p.ID == o.AwardTypeID);
                    return o;
                }).ToArray();
                var pro = Pagination.FromQuery(query);
                ViewData["Pagination"] = pro;
                ViewData["Query"] = query;
                return View(initList);
            }   
        }

        [HttpPost]
        public ActionResult AjaxQuery(AwardQuery query)
        {
            long activityID = Convert.ToInt64(Request.Form["ActivityID"]);
            var awardtypes = Service.Select(new AwardTypeQuery()
            {
                ActivityID = activityID,
                OwnerID = OwnerID,
                Take = PageSize,
            }).ToArray();
            if (!awardtypes.Any())
            {
                ViewData["Pagination"] = Pagination.FromQuery(query);
                ViewData["Query"] = query;
                return PartialView("Award/AwardList");
            }
            else
            {
                query.Take = query.Take ?? PageSize;
                query.OrderField = query.OrderField ?? "LastModifiedAt";
                query.OrderDirection = query.OrderDirection ?? OrderDirection.Desc;
                query.AwardTypeIDs = awardtypes.Select(o => o.ID).OfType<long>().ToArray();
                var initList = Service.Select(query).ToArray();
                initList = initList.Select(o =>
                {
                    o.AwardType = awardtypes.FirstOrDefault(p => p.ID == o.AwardTypeID);
                    return o;
                }).ToArray();
                var pro = Pagination.FromQuery(query);
                ViewData["Pagination"] = pro;
                ViewData["Query"] = query;
                return PartialView("Award/AwardList",initList);
            }   
          
        }

        [HttpPost]
        public JsonResult ChangeState(long id, int state)
        {
            Service.Update(new Award()
            {
                ID = id,State = state
            });
            return new JsonResult()
            {
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                Data = new {success=true}
            };
        }
    }
}

Views/Shared/Activity/ActivityAwardTypes.cshtml
@using DBC.Ors.UI.Web.Mvc
@using DBC.WeChat.Models.Conversation
@model ICollection<DBC.WeChat.Models.Conversation.AwardType>

<div class="sc_ctab sc_top">
    @if (Model.Count == 0)
    {
        Model.Add(new AwardType());
    }
    <table id="AwardList">
        <thead>
            <tr>
                <th class="sc_ctname">奖项名称</th>
                <th class="sc_ctname">奖品名称</th>
                <th class="sc_ctnums">奖项数量</th>
                <th class="sc_ctodds">中奖概率(%)</th>
                <th class="sc_ctlabe">中奖提示</th>
                <th class="sc_ctopea">操作</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Count; i++)
            {
                <tr id="li@(i)">
                    <td class="sc_ctname">
                        <input type="text" name="TypeName@(i)" value="@Model.ToArray()[i].TypeName" /></td>
                    <td class="sc_ctname">
                        <input type="text" name="Name@(i)" value="@Model.ToArray()[i].Name" />
                    </td>
                    <td class="sc_ctnums">
                        <input type="text" name="Count@(i)" value="@Model.ToArray()[i].Count" />
                    </td>
                    <td class="sc_ctodds">
                        <input type="text" name="Probality@(i)" value="@Model.ToArray()[i].Probability" />
                    </td>
                    <td class="sc_ctlabe">
                        <input type="text" name="Reply@(i)" value="@Model.ToArray()[i].Reply" />
                    </td>
                    <td class="sc_ctopea">
                        <a id="Delete@(i)" index="@i" action="DoAjax">删除</a>
                        <input type="hidden" name="ID@(i)" value="@Model.ToArray()[i].ID" />
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <p class="sc_addacty sc_top"><a id="AddAwardType">+ 添加奖项</a></p>
</div>
<div class="hide">
    <input id="AwardTypeCount" name="AwardTypeCount" type="text" value=@(Model.Count) />
</div>

Views/Shared/Activity/ActivityList.cshtml
@using DBC.WeChat.Models.Conversation
@using DBC.WeChat.Services.Components
@using DBC.WeChat.UI.Components
@model IEnumerable<DBC.WeChat.Models.Conversation.Activity>
@{
    var pagination = ViewData["Pagination"] as Pagination;
}
<script type="text/javascript" src="~/Content/Scripts/Conversation/Activity.js"></script>
<table class="prize_set">
    <thead>
        <tr>
            <th class="pt_atype">活动名称</th>
            <th class="pt_name">截止时间</th>
            <th class="pt_ptype">活动状态</th>
            <th class="pt_opea">操作</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var activity in Model)
        {
            <tr>
                <td class="pt_atype">
                    <a onclick="javascript:EditClick(@activity.ID);">@activity.Name</a>
                </td>
                <td class="pt_name">@activity.DeadLineTime</td>
                <td class="pt_ptype"><b id="State@(activity.ID)">@(((ActivityState)activity.State).GetDescription())</b></td>
                <td class="pt_opea">
                    @Html.ActionLink("奖品发放","Index","Award",new {activityID=activity.ID},null)

                    @if (activity.State == (int) ActivityState.Started)
                    {
                        <a id="Change@(activity.ID)" onclick="javascript:ChangeState(@activity.ID,@((int) ActivityState.Stoped));">暂停</a>
                    }
                    else if (activity.State == (int)ActivityState.Init || activity.State == (int)ActivityState.Stoped)
                    {
                        <a id="Change@(activity.ID)" onclick="javascript:ChangeState(@activity.ID,@((int) ActivityState.Started));">启用</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="hide">
    <input type="text" id="AddError" value="@ViewBag.Error"/>
    <input type="text" id="Stop" value="@((int) ActivityState.Started)" 
        des=@((ActivityState.Stoped).GetDescription()) action="启用" /> 
    <input type="text" id="Start" value="@((int) ActivityState.Stoped)" 
        des=@((ActivityState.Started).GetDescription()) action="暂停" /> 
</div>
<div id="pagination">
    @Html.Partial("Pagination", pagination)
</div>

Views/Shared/Activity/ActivityQuery.cshtml
@model DBC.WeChat.Models.Conversation.ActivityQuery


<div class="hide">
    @Html.TextBoxFor(m => m.Take)
    @Html.TextBoxFor(m => m.Skip)
    @Html.TextBoxFor(m => m.OrderField)
    @Html.TextBoxFor(m => m.OrderDirection)
</div>