Controllers/SaleOrderController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using DBC.Ors.Models;
using DBC.Ors.Models.Infrastructures.Shared;
using DBC.Ors.Services;
using DBC.WeChat.Models;
using DBC.WeChat.Models.Infrastructures;
using DBC.WeChat.Models.Sales;
using DBC.WeChat.Services.Components;
using DBC.WeChat.Services.Components.Picture;
using DBC.WeChat.Services.Sales.Components;
using DBC.WeChat.UI.Components;
using DBC.WeChat.UI.Mvc;
using DBC.WeChat.UI.Store.Models;
using DBC.WeChat.UI.Store.Properties;

namespace DBC.WeChat.UI.Store.Controllers
{
    public class SaleOrderController : BaseController
    {
        private int _pageSize = 15;
        private readonly string ftp = ConfigurationManager.AppSettings["ftp"];
        private readonly IPictureService _pictureService = ServiceLocator.Resolve<IPictureService>("Ftp");
        private PictureSize ListSize = ServiceLocator.Resolve<PictureSize>("ListSize");
        private ISaleOrderService saleOrderService = ServiceLocator.Resolve<ISaleOrderService>("SaleOrderService");

        //提示字符串
        private const string SaleOrderCannotEdit = "已作废订单不能编辑";


        public ActionResult Index()
        {
            var query = new SaleOrderQuery()
            {
                OwnerIDs = new long[] { GetOwnerID() },
                Take = _pageSize,
                OrderField = "CreatedAt",
                OrderDirection = OrderDirection.Desc,
            };
            var initList = Service.Select(query).ToArray();
            ViewData["Pagination"] = Pagination.FromQuery(query);
            List<SelectListItem> stateList = new List<SelectListItem>()
                {
                    new SelectListItem()
                        {
                            Value = "-1",
                            Text = "请选择",
                        }
                };
            stateList.AddRange(Enum.GetValues(typeof(OrderState)).Cast<OrderState>().Select(o => new SelectListItem()
            {
                Value = ((int)o).ToString(),
                Text = o.GetDescription(),
            }).ToList());
            ViewData["stateList"] = stateList;
            GetDeliveryMehtods(initList);
            return View(initList);
        }

        public ActionResult AjaxQuery(SaleOrderQuery query)
        {
            if (query == null)
                query = new SaleOrderQuery();

            Boolean hasQueryed = false;
            if (Request.Form["hasQuery"] != null)
            {
                hasQueryed = Convert.ToBoolean(Request.Form["hasQuery"]);
            }
            if (hasQueryed)
            {
                if (query.AmountRange.Left == null && query.AmountRange.Right == null)
                {
                    query.AmountRange = null;
                }
                if (query.CreatedAtRange.Right != null)
                {
                    query.CreatedAtRange.Right = query.CreatedAtRange.Right.Value.AddDays(1);
                }
                if (query.CreatedAtRange.Left == null && query.CreatedAtRange.Right == null)
                {
                    query.CreatedAtRange = null;
                }
                if (query.CodePattern != null)
                {
                    query.CodePattern = query.CodePattern.Trim();
                }
                if (query.NamePattern != null)
                {
                    query.NamePattern = query.NamePattern.Trim();
                }
                if (query.State == -1)
                {
                    query.State = null;
                }
            }
            else
            {
                query.AmountRange = null;
                query.CodePattern = null;
                query.NamePattern = null;
                query.CreatedAtRange = null;
                query.State = null;
            }
            query.States = FilterStates();
            query.OwnerIDs = new long[] { GetOwnerID() };
            query.Take = _pageSize;
            if (string.IsNullOrWhiteSpace(query.OrderField))
            {
                query.OrderField = "CreatedAt";
                query.OrderDirection = OrderDirection.Desc;
            }
            var saleorders = Service.Select(query).ToArray();
            var pro = Pagination.FromQuery(query);
            ViewData["Pagination"] = pro;
            GetDeliveryMehtods(saleorders);
            return PartialView("SaleOrder/OrderList", saleorders);
        }



        public ActionResult Edit(int id)
        {
            try
            {
                var order = Service.Select(new SaleOrderQuery()
                {
                    IDs = new long[] { id },
                    OwnerIDs = new long[] { GetOwnerID() }
                }).FirstOrDefault();
                if (order != null)
                {
                    var Items = Service.Select(new SaleOrderItemQuery()
                    {
                        OrderIDs = new long[] { id },
                        Includes = new string[] { "Specification" },
                    });
                    List<string> paths = new List<string>();
                    foreach (var saleOrderItem in Items)
                    {
                        var pic = Service.SelectOrEmpty(new ProductPictureQuery()
                        {
                            OwnerID = GetOwnerID(),
                            ProductIDs = new long[]{saleOrderItem.Specification.ProductID.Value},
                            IsFirst = true,
                        }).FirstOrDefault();
                        if (pic != null)
                        {
                            paths.Add(System.IO.Path.Combine(ftp, pic.Path, _pictureService.GetName(pic, ListSize)));
                        }
                        else
                        {
                            paths.Add(Resources.DefaultListPicPath);
                        }
                    }
                    ViewData["paths"] = paths;
                    order.Items = Items.ToArray();
                    GetDeliveryMehtods(order);
                    ViewBag.DeliveryMethods = GetDeliveryMethods();
                }
                return View(order);
            }
            catch (Exception e)
            {
                return View("Error", new ErrorView() { message = e.Message });
            }
        }

        [HttpPost]
        public ActionResult Edit(SaleOrder saleOrder)
        {
            if (saleOrder.State != null && saleOrder.State.Value == (int)OrderState.Canceled)
                return View("Error", new ErrorView() { message = SaleOrderCannotEdit });
            try
            {
                ViewBag.DeliveryMethods = GetDeliveryMethods();
                Service.Update(saleOrder);

                //加载订单商品信息
                //*********************************************************//
                var Items = Service.Select(new SaleOrderItemQuery()
                {
                    OrderIDs = new long[] { saleOrder.ID ?? 0 },
                    Includes = new string[] { "Specification" },
                });
                var picList = Service.Select(new ProductPictureQuery()
                {
                    ProductIDs = Items.Select(o => o.Specification.ProductID.Value).ToArray(),
                    IsFirst = true,
                });
                List<string> paths = new List<string>();
                foreach (var saleOrderItem in Items)
                {
                    var pic = Service.SelectOrEmpty(new ProductPictureQuery()
                    {
                        OwnerID = GetOwnerID(),
                        ProductIDs = new long[] { saleOrderItem.Specification.ProductID.Value },
                        IsFirst = true,
                    }).FirstOrDefault();
                    if (pic != null)
                    {
                        paths.Add(System.IO.Path.Combine(ftp, pic.Path, _pictureService.GetName(pic, ListSize)));
                    }
                    else
                    {
                        paths.Add(Resources.DefaultListPicPath);
                    }
                }
                ViewData["paths"] = paths;
                saleOrder.Items = Items.ToArray();
                //*********************************************************//

                return View(saleOrder);
            }
            catch (Exception e)
            {
                return View("Error", new ErrorView() { message = e.Message });
            }
        }

        [HttpPost]
        public JsonResult ChangeState(int originstate, int state, bool isCOD)
        {
            var response = new JsonResult()
            {
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
            };
            try
            {
                //订单状态验证
                if (CheckState(originstate, state, isCOD))
                {
                    var requestIDs = Request.Form.GetValues("ids[]");
                    if (requestIDs != null)
                    {
                        long[] ids = requestIDs.Select(p => Convert.ToInt64(p)).ToArray();
                        var orders = ids.Select(o => new SaleOrder() { ID = o, State = state }).ToArray();
                        if (state == (int)OrderState.Canceled)
                        {
                            foreach (var id in ids)
                            {
                                saleOrderService.Cancel(id);
                            }
                        }
                        else
                        {
                            Service.Update(orders);
                        }
                        response.Data = new
                        {
                            success = true,
                            IDs = ids,
                            StateView = ((OrderState)state).GetDescription(),
                            message = "操作成功"

Views/SaleOrder/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Master.cshtml";
}
@using DBC.WeChat.Models.Infrastructures
@using DBC.WeChat.Models.Sales
@using DBC.WeChat.Services.Components
@using DBC.WeChat.UI.Store.Models
@model DBC.WeChat.Models.Sales.SaleOrder
@section Css{
    <link rel="stylesheet" href="~/Content/css/order.css">
}
@section Script{
    <script src="~/Content/Scripts/SaleOrder/SaleOrder.js" type="text/javascript"></script>
<script src="~/Content/Gridpp/Scripts/CreateControl.js" type="text/javascript"></script>
    <script src="~/Content/Gridpp/Scripts/GRInstall.js" type="text/javascript"></script>
    <script type="text/javascript">
        Install_InsertReport();
    </script>
}

<script type="text/javascript">
    $(function () {
        if ($("#cansave").val() == "False") {
            $("#submit").attr("onclick", "").css({ background: "gray" });;
        }
        $("#DeliveryMethodSelect").find("option[value=" + $("#DeliveryMethodID").val() + "]").attr("selected", true);

        $("#DeliveryMethodSelect").change(function () {
            $("#DeliveryMethodID").attr("value", $(this).find("option:selected").val());
        });
    })
    var Installed = Install_Detect();
</script>
<div class="pg_mm">
    <div class="order_information">
        @using (Html.BeginForm("Edit", "SaleOrder"))
        {
            <div class="oi_title">订单信息</div>
            <img onclick="javascript:window.open('/Content/Gridpp/General/PrintReport.aspx?Report=SaleOrder4.grf&Data=getsaleorderdata.aspx?SaleOrderID='+@Model.ID);"src="~/Content/images/i/printer.png" alt="打印" title="打印订单" style="width: 25px;height: 25px;margin: 4px;cursor: pointer;"/>
            <div class="oi_omain">
                <p><span>订单号：</span>@Model.Code</p>
                <p><span>订单生产时间：</span>@Model.CreatedAt</p>
                <p>
                    <span>订单状态：</span><em id="status@(Model.ID)">@(((OrderState)Model.State).GetDescription())</em>
                    @{
            var isCOD = Model.IsCOD != null && Model.IsCOD.Value;
                    }
                </p>
                <p>
                    <span>订单操作：</span>
                    @{
            if (Model.State == (int)OrderState.ToBePaid)
            {
                        <a href="javascript:changestate([@Model.ID],@((int)OrderState.Canceled),@Model.State,'@isCOD.ToString()');" class="cur">作废</a>
            }
            else if (Model.State == (int)OrderState.ToBeShipped)
            {
                        <a href="javascript:changestate([@Model.ID],@((int)OrderState.ToBeAccept),@Model.State,'@isCOD.ToString()');">发货</a>
                        <a href="javascript:changestate([@Model.ID],@((int)OrderState.Canceled),@Model.State,'@isCOD.ToString()');" class="cur">作废</a>
            }
                    }


                    @*<a href="javascript:changestate([@Model.ID],
                                @((int)OrderState.ToBeAccept),@Model.State,'@isCOD.ToString()');">发货</a>
                    <a href="javascript:changestate([@Model.ID],
                                @((int)OrderState.Finished),@Model.State,'@isCOD.ToString()');">退款</a>
                    <a href="javascript:changestate([@Model.ID],
                                @((int)OrderState.Canceled),@Model.State,'@isCOD.ToString()');"
                        class="cur">作废</a>*@
                </p>
                <div class="hide">@Html.TextBoxFor(m => m.State, new { id = "state" + Model.ID })</div>
            </div>
            <div class="oi_title">收货人信息</div>
            <div class="oi_cmain">
                <div class="oi_m">
                    <span>收货人：</span>@Html.TextBoxFor(m => m.Name)
                </div>
                <div class="oi_m">
                    <span>联系电话：</span>@Html.TextBoxFor(m => m.Mobile)
                </div>
                <div class="oi_m">
                    <span>收货人地址：</span>
                    @Html.Partial("District", Model.AreaID.Value)
                </div>
                <div class="hide">
                    @Html.TextBoxFor(m => m.AreaID,new { id = "targetDis" })
                </div>
                <div class="oi_m">
                    <span>详细地址：</span>@Html.TextBoxFor(m => m.Address)
                </div>
            </div>
            <div class="oi_title">物流信息</div>
            <div class="oi_cmain">
                <div class="oi_m">
                    <span>快递名称：</span>
                    <select id="DeliveryMethodSelect">
                        @{
            var items = (DeliveryMethod[])ViewBag.DeliveryMethods;
            if (items != null && items.Any())
            {
                foreach (var item in items)
                {
                            <option value="@item.ID">@item.Name</option>
                }
            }
                        }
                    </select>
                    <div class="hide">
                        @Html.TextBoxFor(m => m.DeliveryMethodID)
                    </div>
                </div>
                <div class="oi_m">
                    <span>快递费用：</span><b>&yen;@Html.DisplayTextFor(m => m.DeliveryFee)</b>
                </div>
                <div class="oi_m">
                    <span>快递单号：</span>@Html.TextBoxFor(m => m.DeliveryCode)
                </div>
                <div class="oi_m"><a id="submit" onclick="SubmitData();">保存</a></div>
            </div>
            <div class="oi_title">商品信息</div>
        }

        <div class="oi_list">
            <table class="oi_tab">
                <thead>
                    <tr>
                        <th class="oi_name">商品名称</th>
                        <th class="oi_norm">规格</th>
                        <th class="oi_nums">商品数量</th>
                        <th class="oi_reta">商品单价</th>
                        <th class="oi_coun">商品总价</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        var paths = (List<string>)ViewData["paths"];
                        int count = 0;
                        int index = 0;
                        decimal totalamount = 0;
                        foreach (var item in Model.Items)
                        {
                            count += item.Quantity.Value;
                            if (item.Specification != null)
                            {
                                totalamount += (item.Specification.Price * item.Quantity).Value;
                        <tr>
                            <td class="oi_name">
                                <a href="javascript:;">
                                    <img src="@paths[index]" />
                                </a>
                                <p>@Html.ActionLink(item.Specification.ProductName ?? " ", "Edit", "Product", new { id = item.Specification.ProductID }, new { })</p>
                            </td>
                            <td class="oi_norm"><b>@item.Specification.Name</b></td>
                            <td class="oi_nums">@item.Quantity</td>
                            <td class="oi_reta"><b>&yen;@item.Specification.Price</b></td>
                            <td class="oi_coun"><b>&yen;@(item.Specification.Price * item.Quantity)</b></td>
                        </tr>
                                index++;
                            }
                        }
                    }
                </tbody>
            </table>
        </div>
        <div class="hide">
            @{
                var cansave = Model.State != null && Model.State.Value != (int)OrderState.Canceled
                    && Model.State.Value != (int)OrderState.ToBeAccept&&Model.State.Value!=(int)OrderState.Finished;
            }
            <input id="cansave" value=@cansave.ToString() />
        </div>
        <div class="oi_count">
            <span>商品数量：@count</span><b>合计价格：<font>&yen;@totalamount</font></b>
        </div>
    </div>
</div>

Views/SaleOrder/Index.cshtml
@{
    ViewBag.Title = "订单管理";
    Layout = "~/Views/Shared/_Master.cshtml";
}

@using DBC.WeChat.Models.Sales
@model ICollection<DBC.WeChat.Models.Sales.SaleOrder>

@section Css{
    <link rel="stylesheet" href="~/Content/css/order.css">
<link type="text/css" rel="stylesheet" href="~/Content/css/datePicker.css" />
<link rel="stylesheet" type="text/css" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
}
<script src="~/Content/Scripts/SaleOrder/SaleOrder.js" type="text/javascript"></script>
<script type="text/javascript" src="http://code.jquery.com/ui/1.10.3/jquery-ui.min.js"></script>
  <script type="text/javascript" 
        src="~/Content/Libraries/jQuery/jquery.unobtrusive-ajax.min.js" ></script>

@using (Ajax.BeginForm("AjaxQuery", "SaleOrder", null, new AjaxOptions()
      {
          HttpMethod = "POST",
          InsertionMode = InsertionMode.Replace,
          UpdateTargetId = "orderList",
          OnSuccess = "QuerySuccess",
      }, new { ID = "queryForm", name = "queryForm" }))
{
    @Html.Partial("SaleOrder/OrderQuery",new SaleOrderQuery())
    <div class="pg_mm">
        <div id="orderList">
            @Html.Partial("SaleOrder/OrderList", Model)
        </div>
    </div>
}